# Generated by Django 5.1.3 on 2024-12-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('requirements', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=255)),
            ],
        ),
    ]
