# Generated by Django 5.1.3 on 2024-12-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='limit_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='min_age',
            field=models.SmallIntegerField(default=18),
            preserve_default=False,
        ),
    ]
