# Generated by Django 5.1.3 on 2024-12-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_limit_date_event_min_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('Fútbol', 'Fútbol'), ('Baloncesto', 'Baloncesto'), ('Tenis', 'Tenis'), ('Natación', 'Natación')], max_length=255),
        ),
    ]
